services:
  mcp-proxy-manager:
    build:
      context: ./mcp-proxy-manager
      dockerfile: Dockerfile
    container_name: mcp-proxy-manager
    restart: unless-stopped
    # Relaxed security for reliable multi-transport operation
    read_only: false
    user: mcpuser  # Non-root user
    # Relaxed security context for MCP tool flexibility
    security_opt:
      - no-new-privileges:false
      - seccomp:unconfined
    # Minimal capability restrictions for reliable operation
    # Minimal tmpfs mounts - reduced overhead for performance
    tmpfs:
      - /tmp:exec,size=1g
      - /var/log/mcp-proxy-manager:size=100m
    ports:
      # Bind only to localhost for security (change if external access needed)
      - "127.0.0.1:${MANAGER_PORT:-3001}:${MANAGER_PORT:-3001}"
      # MCP Proxy port range - bind to localhost for security (expanded for multi-transport)
      - "127.0.0.1:${PORT_RANGE_START:-50000}-${PORT_RANGE_END:-50300}:${PORT_RANGE_START:-50000}-${PORT_RANGE_END:-50300}"
    volumes:
      # Mount your Claude Desktop config (read-only for security)
      - ./config/claude_desktop_config.json:/config/claude_desktop_config.json:ro
      # Environment files (encrypted, writable) - mounted to read-only tmpfs
      - ./config:/config:ro
      # Persist user home directory for environment variables and user data
      - mcpuser-home:/home/mcpuser:rw
    # Docker secrets for sensitive data (commented - can be enabled)
    # secrets:
    #   - webui_secret_key
    #   - source: claude_config
    #     target: /run/secrets/claude_config.json
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MANAGER_PORT=${MANAGER_PORT:-3001}
      - CLAUDE_CONFIG_PATH=${CLAUDE_CONFIG_PATH:-/config/claude_desktop_config.json}
      - MCP_PROXY_TYPE=${MCP_PROXY_TYPE:-mcpo}
      - MCP_PROXY_MODE=${MCP_PROXY_MODE:-unified} # individual or 'unified' for route-based single MCPO
      - PORT_RANGE_START=${PORT_RANGE_START:-50000}
      - PORT_RANGE_END=${PORT_RANGE_END:-50300}
      # Multi-Transport Configuration
      - ENABLE_MULTI_TRANSPORT=${ENABLE_MULTI_TRANSPORT:-false}
      - TRANSPORT_STREAMABLE=${TRANSPORT_STREAMABLE:-true}
      - TRANSPORT_WEBSOCKET=${TRANSPORT_WEBSOCKET:-true}
      - TRANSPORT_SSE=${TRANSPORT_SSE:-true}
      - TRANSPORT_OPENAPI=${TRANSPORT_OPENAPI:-true}
      # Cache and tool directories - use user home directory (best practice)
      - UV_CACHE_DIR=/home/mcpuser/.cache/uv
      - UV_TOOL_DIR=/home/mcpuser/.local/share/uv/tools
      - NPM_CONFIG_CACHE=/home/mcpuser/.cache/npm
      - PLAYWRIGHT_BROWSERS_PATH=/home/mcpuser/.cache/playwright
      # Ensure npm uses an exec-able tmp dir (avoid noexec mounts)
      - NPM_CONFIG_TMP=/app/tmp
      - TMPDIR=/app/tmp
    # Resource limits for security and stability (enhanced for multi-transport)
    deploy:
      resources:
        limits:
          memory: 8G        # Increased for multi-transport (37 processes validated)
          cpus: "4.0"       # Increased for concurrent multi-transport processing
          pids: 4096        # Increased for multi-transport processes (37 processes)
        reservations:
          memory: 512M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    driver: bridge
  mcp-internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
    # Remove 'internal: true' to allow external access for OpenWebUI integration
    # Set to 'internal: true' for complete network isolation if not needed

# Named volumes for persistent storage
volumes:
  mcpuser-home:
    driver: local

# Docker secrets configuration (commented - uncomment to enable)
# secrets:
#   webui_secret_key:
#     file: ./secrets/webui_secret_key.txt
#   claude_config:
#     file: ./secrets/claude_desktop_config.json